//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAJCYCL_LOG
    {
        public string LOG_STS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_no { get; set; }
        public string Sap_Asset_No { get; set; }
        public Nullable<decimal> Total_Cycle { get; set; }
        public Nullable<decimal> Change_Cycle { get; set; }
        public string ForCycle { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
