//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASSETS
    {
        public string Comp_Cd { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_Name { get; set; }
        public string Ast_Kind1 { get; set; }
        public string Ast_Kind2 { get; set; }
        public string Ast_Kind3 { get; set; }
        public string Upkeep_Kind { get; set; }
        public string Debit_Kind { get; set; }
        public string First_Ast_Cd { get; set; }
        public decimal Maintain_Charges { get; set; }
        public decimal Repair_Charges { get; set; }
        public decimal Staging_Charges { get; set; }
        public decimal Sum_Usual_Limit { get; set; }
        public decimal Win_Usual_Limit { get; set; }
        public decimal Sum_Emc_Limit { get; set; }
        public decimal Win_Emc_Limit { get; set; }
        public string Provider_No { get; set; }
        public decimal Costdown_B { get; set; }
        public decimal Costdown_C { get; set; }
        public decimal Costdown_D { get; set; }
        public string Upkeep_Cal_Type { get; set; }
        public decimal Ast_Limit { get; set; }
        public string Close_Date { get; set; }
        public string Sap_Project_No { get; set; }
        public string Spc_Asset_Kind { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public decimal Staging_Month { get; set; }
    }
}
