//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBUPART
    {
        public string Comp_Cd { get; set; }
        public string Part_No { get; set; }
        public string Part_Name { get; set; }
        public string Part_Name_En { get; set; }
        public string Unit { get; set; }
        public string Spec { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string SBI { get; set; }
        public string Asset_Cd { get; set; }
        public string Send_Type { get; set; }
        public string Order_Unit { get; set; }
        public string Sale_Unit { get; set; }
        public Nullable<decimal> Safe_Inventory { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
