//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCALLOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TCALLOG()
        {
            this.TCallLogRecord = new HashSet<TCallLogRecord>();
            this.TCallogCourse = new HashSet<TCallogCourse>();
            this.TVenderTechnician = new HashSet<TVenderTechnician>();
        }
    
        public string Comp_Cd { get; set; }
        public string Sn { get; set; }
        public string Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Fi_Date { get; set; }
        public string Caller_Id { get; set; }
        public string Caller_Name { get; set; }
        public string Ast_Kind1 { get; set; }
        public string Ast_Kind2 { get; set; }
        public string Ast_Kind3 { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_No { get; set; }
        public string Sap_Asset_No { get; set; }
        public string Damage_No { get; set; }
        public string Vender_Cd { get; set; }
        public string Call_Level { get; set; }
        public string Call_Desc { get; set; }
        public string Remark_Add { get; set; }
        public string Fv_Date { get; set; }
        public string Fd_Date { get; set; }
        public string Fa_Date { get; set; }
        public string Arrive_Date { get; set; }
        public string Fc_Date { get; set; }
        public string Finish_Id { get; set; }
        public string Eng_No { get; set; }
        public string Damage_Proc_No { get; set; }
        public string Damage_Proc_No1 { get; set; }
        public string Damage_Proc_No2 { get; set; }
        public string Work_Desc { get; set; }
        public string Delay_Sts { get; set; }
        public string Work_Id { get; set; }
        public string Calamity_Type { get; set; }
        public string Close_User { get; set; }
        public string Close_Date { get; set; }
        public string VndEng_Id { get; set; }
        public string AppClose_Date { get; set; }
        public byte Close_Sts { get; set; }
        public byte Trans_Flag { get; set; }
        public string Count_Sts { get; set; }
        public Nullable<decimal> Coffee_Cup { get; set; }
        public string Create_User_Id { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public string Fr_Date { get; set; }
        public string Return_Date { get; set; }
        public int TimePoint { get; set; }
    
        public virtual TAcceptedLog TAcceptedLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCallLogRecord> TCallLogRecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCallogCourse> TCallogCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVenderTechnician> TVenderTechnician { get; set; }
    }
}
