//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCFMTN
    {
        public string Comp_Cd { get; set; }
        public string CF_Sn { get; set; }
        public string Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Fi_Date { get; set; }
        public string Caller_Id { get; set; }
        public string Caller_Name { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_No { get; set; }
        public string Sap_Asset_No { get; set; }
        public string Vender_Cd { get; set; }
        public string Fv_Date { get; set; }
        public string Fd_Date { get; set; }
        public string Arrive_Date { get; set; }
        public string Maintain_Date { get; set; }
        public string Maintain_Level { get; set; }
        public decimal TotalCap_Quantity { get; set; }
        public decimal Cap_Quantity { get; set; }
        public decimal Cap_Maintain { get; set; }
        public decimal HotCups { get; set; }
        public decimal ColdCups { get; set; }
        public decimal NextMaintain_Cups { get; set; }
        public decimal Maintain_Charges { get; set; }
        public string Work_Desc { get; set; }
        public decimal Species { get; set; }
        public string Finish_Id { get; set; }
        public string Close_User { get; set; }
        public string Finish_Date { get; set; }
        public byte Trans_Flag { get; set; }
        public string Create_User_Id { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public Nullable<decimal> Coffee_Clean { get; set; }
        public Nullable<decimal> Milk_Clean { get; set; }
    }
}
