//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCMPDAT
    {
        public string Comp_Cd { get; set; }
        public string Comp_Name { get; set; }
        public string Comp_Short { get; set; }
        public string Comp_Addr { get; set; }
        public string Email_Account { get; set; }
        public decimal Sort_Seq { get; set; }
        public decimal Beg_Summer { get; set; }
        public decimal End_Summer { get; set; }
        public decimal Last_Call_To_Act { get; set; }
        public decimal Last_Proj_To_Act { get; set; }
        public decimal Last_Vene_To_Act { get; set; }
        public string Chk_Str_Cd { get; set; }
        public string Chk_Str_Nm { get; set; }
        public string Auto_Ast_No { get; set; }
        public string Inv_BDate { get; set; }
        public string Inv_EDate { get; set; }
        public string Voucher_Writer { get; set; }
        public decimal Comp_Sts { get; set; }
        public byte[] Comp_Image { get; set; }
        public byte[] Base_Maps { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
