//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENGSTK
    {
        public string Comp_Cd { get; set; }
        public string FileName { get; set; }
        public string SendFile_Date { get; set; }
        public string Send_Flag { get; set; }
        public string Rfno { get; set; }
        public string Lno { get; set; }
        public string Status { get; set; }
        public string ErrMSG { get; set; }
    }
}
