//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENGMST_LOG
    {
        public string LOG_STS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string Comp_Cd { get; set; }
        public string Z_O { get; set; }
        public string Eng_No { get; set; }
        public string Eng_Name { get; set; }
        public string Tel_No { get; set; }
        public string Emc_Tel { get; set; }
        public string Email { get; set; }
        public string Is_Manager { get; set; }
    }
}
