//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINVMST
    {
        public string Comp_Cd { get; set; }
        public decimal Y_M { get; set; }
        public string Invoice_No { get; set; }
        public string Invoice_Date { get; set; }
        public string Exp_Kind { get; set; }
        public string Debit_Kind { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Vender_Id { get; set; }
        public decimal Inv_Amt { get; set; }
        public decimal Tax_Amt { get; set; }
        public decimal Inv_Tot_Amt { get; set; }
        public string Vender_Cd { get; set; }
        public string Project_No { get; set; }
    }
}
