//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TKNDHST
    {
        public decimal Y_M { get; set; }
        public long LayKind_Id { get; set; }
        public decimal Parent_Id { get; set; }
        public string LayKind_Name { get; set; }
        public decimal Node_Seq { get; set; }
        public string Comp_Cd { get; set; }
        public string Parent_Tree { get; set; }
        public decimal Kind_Level { get; set; }
        public decimal Data_Type { get; set; }
        public decimal Numeric_Kind { get; set; }
    }
}
