//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPGMAUT
    {
        public string Comp_Cd { get; set; }
        public string Pgm_Id { get; set; }
        public string Role_Id { get; set; }
        public string Run_Aut { get; set; }
        public decimal Run_Level { get; set; }
        public string Report_Aut { get; set; }
        public string Export_Aut { get; set; }
        public string O_Run_Aut { get; set; }
        public decimal O_Run_Level { get; set; }
        public string O_Export_Aut { get; set; }
        public string O_Report_Aut { get; set; }
    }
}
