//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPGMMST
    {
        public string Pgm_Id { get; set; }
        public string Pgm_Name { get; set; }
        public decimal Pgm_Kind { get; set; }
        public decimal Pgm_Type { get; set; }
        public decimal Pgm_Sts { get; set; }
        public string CS_Sts { get; set; }
        public string Browse_Sts { get; set; }
        public string Parent_Id { get; set; }
        public Nullable<short> Menu_Seq { get; set; }
    }
}
