//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPRJDTL
    {
        public string Project_No { get; set; }
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Item_No { get; set; }
        public string Act_No { get; set; }
        public string Asset_Cd { get; set; }
        public string Debit_Kind { get; set; }
        public decimal Direct_Amt { get; set; }
        public decimal Join_Amt { get; set; }
        public decimal Comp_Amt { get; set; }
        public decimal Tot_Amt { get; set; }
        public string Pingdan_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
