//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTAIPD
    {
        public long IPD_ID { get; set; }
        public long Parent_IPM_ID { get; set; }
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Asset_Cd { get; set; }
        public string Machine_Type { get; set; }
        public short Asset_SNum { get; set; }
        public string Asset_No { get; set; }
        public string Sap_Asset_No { get; set; }
        public string Vender_Cd { get; set; }
        public decimal Begin_YM { get; set; }
        public System.DateTime Mod_Date { get; set; }
        public string Proc_Sts { get; set; }
        public string ErrMsg { get; set; }
        public string Update_Date { get; set; }
        public string Update_User { get; set; }
    }
}
