//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTRPWR
    {
        public decimal YYMM { get; set; }
        public string E_No { get; set; }
        public string E_Code { get; set; }
        public string E_Type { get; set; }
        public string Line_No { get; set; }
        public decimal Regular_Capacity { get; set; }
        public decimal Regular_Max_Capacity { get; set; }
        public decimal Casual_Max_Capacity { get; set; }
        public decimal Helf_Max_Capacity { get; set; }
        public decimal Duty_Factor { get; set; }
        public decimal Regular_Degree { get; set; }
        public decimal Casual_Degree { get; set; }
        public decimal Helf_Degree { get; set; }
        public decimal Base_Fee { get; set; }
        public decimal Flow_Fee { get; set; }
        public decimal Share_Fee { get; set; }
        public decimal Delay_Fee { get; set; }
        public decimal Total_Fee { get; set; }
        public decimal Surcharger { get; set; }
        public decimal E_Day { get; set; }
        public string E_Cust_Name { get; set; }
        public string E_Cust_Addr { get; set; }
        public decimal Casual_Capacity { get; set; }
        public string E_Cust_Addr2 { get; set; }
        public decimal Pre_Fee_11 { get; set; }
        public Nullable<decimal> Used_Day { get; set; }
    }
}
