//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTNSCALH
    {
        public long File_Seq { get; set; }
        public string Create_Date { get; set; }
        public string Comp_Cd { get; set; }
        public string Sn { get; set; }
        public string Trans_Date { get; set; }
        public int Trans_Count { get; set; }
        public string ERR_Notify_Date { get; set; }
        public string Message { get; set; }
        public string SendFlag { get; set; }
        public byte Trans_Sts { get; set; }
        public string Vender_Cd { get; set; }
        public string Z_O { get; set; }
        public string Zo_Name { get; set; }
        public string D_O { get; set; }
        public string Do_Name { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public string Store_Kind { get; set; }
        public string Tel_No { get; set; }
        public string Store_Addr { get; set; }
        public string Caller { get; set; }
        public string Fi_Date { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_Name { get; set; }
        public string Asset_No { get; set; }
        public string Sap_Asset_No { get; set; }
        public decimal Begin_YM { get; set; }
        public string Damage_No { get; set; }
        public string Damage_Desc { get; set; }
        public string Call_Level { get; set; }
        public string Call_Desc { get; set; }
        public string Remark_Add { get; set; }
        public string Fv_Date { get; set; }
        public string Fd_Date { get; set; }
        public string Eng_No { get; set; }
        public string Eng_Name { get; set; }
        public string Eng_Tel_No { get; set; }
        public decimal Arrive_Hour { get; set; }
        public decimal Comp_Limit { get; set; }
    }
}
