//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNDMEM
    {
        public long Data_Seq { get; set; }
        public string Comp_Cd { get; set; }
        public string Vender_Cd { get; set; }
        public string Date_From { get; set; }
        public string Date_To { get; set; }
        public string Notice_Title { get; set; }
        public string Notice_Contain { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
