//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNOTICE
    {
        public long Issue_ID { get; set; }
        public string Comp_Cd { get; set; }
        public string Issue_Vender { get; set; }
        public string Issue_Date { get; set; }
        public string Issue_Time { get; set; }
        public string Issue_User { get; set; }
        public string Bullentin_No { get; set; }
        public string Bullentin_Type { get; set; }
        public string Bullentin_Subject { get; set; }
        public string Bullentin_Desc { get; set; }
        public long File_Seq { get; set; }
        public Nullable<long> Doc_Seq { get; set; }
        public string Update_Date { get; set; }
        public string Update_User { get; set; }
    }
}
