//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVOUCH
    {
        public string Comp_Cd { get; set; }
        public string Voucher_No { get; set; }
        public string Voucher_Date { get; set; }
        public decimal Voucher_Seq { get; set; }
        public string Credit_Kind { get; set; }
        public string Act_No { get; set; }
        public string Post_Code { get; set; }
        public string Voucher_Sum { get; set; }
        public decimal Amt { get; set; }
        public string Z_O { get; set; }
        public string Vender_Id { get; set; }
        public string Cost_Center { get; set; }
        public string Data_Source { get; set; }
        public string Invoice_No { get; set; }
        public string Invoice_Date { get; set; }
        public string Debit_Kind { get; set; }
        public decimal Inv_Amt { get; set; }
        public decimal Inv_Tax { get; set; }
        public string Voucher_Writer { get; set; }
        public string Item_Type { get; set; }
        public string Sap_Project_No { get; set; }
    }
}
