//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVUPART
    {
        public string Sn { get; set; }
        public byte Seq { get; set; }
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public Nullable<System.DateTime> User_Date { get; set; }
        public string Asset_Cd { get; set; }
        public string Part_No { get; set; }
        public string Part_Spec { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Repair_Hours { get; set; }
        public Nullable<decimal> Repair_Price { get; set; }
        public Nullable<decimal> Tot_Amt { get; set; }
    }
}
