//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.AspNet.Identity.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TZOCODE
    {
        public string Comp_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Zo_Name { get; set; }
        public string Do_Name { get; set; }
        public string Close_Date { get; set; }
        public string Zo_Type { get; set; }
        public string Zo_Ast_Cd { get; set; }
        public string Upkeep_Sts { get; set; }
        public string Call_Sts { get; set; }
        public string Prj_Sts { get; set; }
        public string Act_Sts { get; set; }
    }
}
