//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBFYOUM
    {
        public string Comp_Cd { get; set; }
        public decimal Seq_No { get; set; }
        public string Asset_Cd { get; set; }
        public decimal Start_YM { get; set; }
        public decimal End_YM { get; set; }
        public decimal No_Rebate_Cnt { get; set; }
        public string Rebate_Date { get; set; }
    }
}
