//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCALEXT
    {
        public string Comp_Cd { get; set; }
        public string Sn { get; set; }
        public decimal Step_No { get; set; }
        public string Rcv_Date { get; set; }
        public string Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Urge_Name { get; set; }
        public string Caller_Id { get; set; }
        public string Call_Mark { get; set; }
        public string Create_User { get; set; }
        public string Create_Time { get; set; }
    }
}
