//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDAYCTL
    {
        public long Eng_Id { get; set; }
        public string Comp_Cd { get; set; }
        public string Z_O { get; set; }
        public string Zo_Name { get; set; }
        public string D_O { get; set; }
        public string Do_Name { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public string Store_Kind { get; set; }
        public string Store_Addr { get; set; }
        public string Eng_Type { get; set; }
        public string Measure_Vendor { get; set; }
        public string Build_Vendor { get; set; }
        public string Comp_Designer { get; set; }
        public string Expander { get; set; }
        public string Zo_Designer { get; set; }
        public string Zo_Eng { get; set; }
        public string Rent { get; set; }
        public Nullable<int> PSD { get; set; }
        public string Call_Measure_Date { get; set; }
        public string Measure_Done_Date { get; set; }
        public string Contract_Date { get; set; }
        public string Apply_Img_Date { get; set; }
        public string Zo_Img_To_Comp { get; set; }
        public string Comp_Img_Done_Date { get; set; }
        public string VP_Img_Confirm_Date { get; set; }
        public string Boss_Confirm_Date { get; set; }
        public string Design_Feedback { get; set; }
        public string Expect_Cash_Back_Date { get; set; }
        public string Real_Cash_Back_Date { get; set; }
        public string Apply_Power_Status { get; set; }
        public string Apply_Power_Date { get; set; }
        public string Expect_Closing_Date { get; set; }
        public string Real_Closing_Date { get; set; }
        public string Expect_Tenant_Date { get; set; }
        public string Real_Tenant_Date { get; set; }
        public string Eng_Work_Date { get; set; }
        public string LYIMG_Date { get; set; }
        public string Filing_Date { get; set; }
        public Nullable<int> Expand_Shop_Day { get; set; }
        public Nullable<int> Repair_Img_Day { get; set; }
        public Nullable<int> Landlord_Work_Day { get; set; }
        public Nullable<int> Structure_Identify_Day { get; set; }
        public Nullable<int> Structure_Fix_Day { get; set; }
        public Nullable<int> Suspend_Work_Day { get; set; }
        public string Work_Done_Date { get; set; }
        public string Machine_On_Date { get; set; }
        public string Power_Send_Date { get; set; }
        public string Open_Date { get; set; }
        public string Remark { get; set; }
        public string Is_Close { get; set; }
        public string Create_User { get; set; }
        public string Create_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
