//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDeviceSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDeviceSchedule()
        {
            this.TDeviceScheduleDetail = new HashSet<TDeviceScheduleDetail>();
        }
    
        public int Seq { get; set; }
        public string Project_Name { get; set; }
        public string Purpose { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public Nullable<System.DateTime> LeaveDate { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public string Proposal_User { get; set; }
        public string Proposal_Unit { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TDeviceScheduleDetail> TDeviceScheduleDetail { get; set; }
    }
}
