//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDeviceScheduleDetail
    {
        public int DeviceScheduleSeq { get; set; }
        public string Store_Name { get; set; }
        public string Z_O { get; set; }
        public string Zo_Name { get; set; }
        public string D_O { get; set; }
        public string Do_Name { get; set; }
        public string Remark { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual TDeviceSchedule TDeviceSchedule { get; set; }
    }
}
