//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TELEPAR
    {
        public string Key_Cd { get; set; }
        public decimal Unit_Fee_01 { get; set; }
        public decimal Unit_Fee_02 { get; set; }
        public decimal Unit_Fee_03 { get; set; }
        public decimal Unit_Fee_04 { get; set; }
        public decimal Unit_Fee_05 { get; set; }
        public decimal Unit_Fee_06 { get; set; }
        public decimal Unit_Fee_07 { get; set; }
        public decimal Unit_Fee_08 { get; set; }
        public decimal Unit_Fee_09 { get; set; }
        public decimal Unit_Fee_10 { get; set; }
        public decimal Unit_Fee_11 { get; set; }
        public decimal Unit_Fee_12 { get; set; }
        public decimal Chang_Unit_Fee { get; set; }
        public Nullable<decimal> FC_Seeting { get; set; }
        public Nullable<decimal> Line_Costs { get; set; }
    }
}
