//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINVDTL
    {
        public string Comp_Cd { get; set; }
        public decimal Y_M { get; set; }
        public string Invoice_No { get; set; }
        public decimal Inv_Item_Seq { get; set; }
        public string Exp_Kind { get; set; }
        public string Debit_Kind { get; set; }
        public string Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Source_No { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_No { get; set; }
        public string Sap_Asset_No { get; set; }
        public string Act_No { get; set; }
        public decimal Direct_Amt { get; set; }
        public decimal Join_Amt { get; set; }
        public decimal Comp_Amt { get; set; }
        public decimal Tot_Amt { get; set; }
        public string Cost_Center { get; set; }
        public string Voucher_Desc { get; set; }
        public string Voucher_No { get; set; }
        public Nullable<decimal> Voucher_Item { get; set; }
        public string Pingdan_Date { get; set; }
        public string Sap_Project_No { get; set; }
    }
}
