//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLVKIND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TLVKIND()
        {
            this.TLVCREP = new HashSet<TLVCREP>();
            this.TLVKIND1 = new HashSet<TLVKIND>();
        }
    
        public string Comp_Cd { get; set; }
        public string Asset_Cd { get; set; }
        public string Kind_Cd { get; set; }
        public byte Type_Id { get; set; }
        public string Parent_Id { get; set; }
        public short Menu_Seq { get; set; }
        public string Kind_Name { get; set; }
        public string Kind_Mark { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLVCREP> TLVCREP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TLVKIND> TLVKIND1 { get; set; }
        public virtual TLVKIND TLVKIND2 { get; set; }
    }
}
