//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLYIMGM
    {
        public string Lay_Sn { get; set; }
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string D_O { get; set; }
        public string Wk_Date { get; set; }
        public string Supervisor { get; set; }
        public string Fd_Date { get; set; }
        public string Cfm_Date { get; set; }
        public Nullable<decimal> New_Power { get; set; }
        public string Save_Reason { get; set; }
        public decimal Limit_Sts { get; set; }
        public decimal Close_Sts { get; set; }
        public decimal Work_Type { get; set; }
        public string Wk_Save_User { get; set; }
        public string Wk_Save_Date { get; set; }
        public string Close_User { get; set; }
        public string Close_Date { get; set; }
        public string Create_User { get; set; }
        public string Create_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
