//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAPERS
    {
        public long Paper_Id { get; set; }
        public string Comp_Cd { get; set; }
        public string Paper_No { get; set; }
        public string Paper_Type { get; set; }
        public string Paper_Title { get; set; }
        public string Paper_Detail { get; set; }
        public long Read_Counts { get; set; }
        public Nullable<long> File_Seq { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
