//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSENDMAILVND
    {
        public string Comp_Cd { get; set; }
        public string Comp_Email { get; set; }
        public string Sn { get; set; }
        public string Z_O { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public string Close_Date { get; set; }
        public string Vender_Cd { get; set; }
        public string Vender_Name { get; set; }
        public string Vender_Emai { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_Name { get; set; }
        public string Eng_No { get; set; }
        public string Eng_Name { get; set; }
        public string Eng_Email { get; set; }
        public string Manager_EngNo { get; set; }
        public string Manager_EngName { get; set; }
        public string Manager_Email { get; set; }
        public string Fc_Date { get; set; }
        public string Finish_Id { get; set; }
        public string Fd_Date { get; set; }
        public Nullable<System.DateTime> SendMail_Date { get; set; }
        public Nullable<short> Send_Flag { get; set; }
        public System.DateTime InsertDate { get; set; }
    }
}
