//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTRMOD_LOG
    {
        public string LOG_STS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string Comp_Cd { get; set; }
        public string Create_Date { get; set; }
        public string Mod_Type { get; set; }
        public string Old_Store { get; set; }
        public string Old_Type { get; set; }
        public string New_Store { get; set; }
        public string New_Type { get; set; }
        public string Owner_Mobile { get; set; }
        public string Owner_Name { get; set; }
        public string Mod_Date { get; set; }
        public string Proc_Sts { get; set; }
        public string Create_User { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public int ModID { get; set; }
        public string Mod_Time_Sw { get; set; }
        public string Open_Date { get; set; }
        public string Expand_Type { get; set; }
    }
}
