//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSTRMST
    {
        public string Comp_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public string Store_Kind { get; set; }
        public string Open_Date { get; set; }
        public string Close_Date { get; set; }
        public string Old_Store_Cd { get; set; }
        public string Z_O { get; set; }
        public string Zo_Name { get; set; }
        public string D_O { get; set; }
        public string Do_Name { get; set; }
        public string Tel_No { get; set; }
        public string Store_Addr { get; set; }
        public string Eng_No { get; set; }
        public string Owner_Mobile { get; set; }
        public string Owner_Name { get; set; }
        public decimal Square_Feet { get; set; }
        public string ECust_Type { get; set; }
        public string ECust_Name { get; set; }
        public string E_No { get; set; }
        public string E_Code { get; set; }
        public decimal Regular_Capacity { get; set; }
        public string Line_No { get; set; }
        public string E_Code_Memo { get; set; }
        public string P_Area_Id { get; set; }
        public string Area_Id { get; set; }
        public string Trans_Date { get; set; }
        public string Rm_OpenDate { get; set; }
        public string PS_Sts { get; set; }
        public string Mod_Date { get; set; }
        public string Apply_Power_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
