//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSYSDAT_LOG
    {
        public string LOG_STS { get; set; }
        public Nullable<System.DateTime> LOG_DATE { get; set; }
        public string Key_Cd { get; set; }
        public string Smpt_Name { get; set; }
        public string Send_Mail { get; set; }
        public string SendMail_Id { get; set; }
        public string Mail_Password { get; set; }
        public decimal Pwd_Cycle { get; set; }
        public decimal Pwd_Times { get; set; }
        public string Err_Recv_Mail { get; set; }
        public string CC_Mail { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
