//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSRMST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSRMST()
        {
            this.TUSRVENRELATION = new HashSet<TUSRVENRELATION>();
        }
    
        public string User_Id { get; set; }
        public string User_Name { get; set; }
        public string Comp_Cd { get; set; }
        public string Z_O { get; set; }
        public string Vender_Id { get; set; }
        public string Provider_No { get; set; }
        public string Role_Id { get; set; }
        public string Email_Account { get; set; }
        public string Tel_No { get; set; }
        public string Emc_Tel { get; set; }
        public string Spec_Ctrl { get; set; }
        public string Id_Sts { get; set; }
        public string Vender_Name { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public string PageAuth { get; set; }
    
        public virtual TSYSROL TSYSROL { get; set; }
        public virtual TUSRDTL TUSRDTL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TUSRVENRELATION> TUSRVENRELATION { get; set; }
    }
}
