//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNDUSR
    {
        public string VndEng_Id { get; set; }
        public string Eng_Name { get; set; }
        public string Pass_Wd { get; set; }
        public string Id_Kind { get; set; }
        public string Is_RcvPush { get; set; }
        public string Push_Id { get; set; }
        public string Mobile_Type { get; set; }
        public string Device_Id { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string Pwd_Chg_Time { get; set; }
        public string UserToken { get; set; }
        public decimal ChgPas_Sts { get; set; }
        public string Id_Sts { get; set; }
        public string Create_User { get; set; }
        public string Create_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
    }
}
