//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVNDENG
    {
        public string Comp_Cd { get; set; }
        public string Vender_Cd { get; set; }
        public string Eng_No { get; set; }
        public string Eng_Name { get; set; }
        public string VndGrp_Id { get; set; }
        public string Mobile_Tel { get; set; }
        public Nullable<decimal> Mobile_Type { get; set; }
        public string Email_Account { get; set; }
        public string Is_Assign { get; set; }
        public Nullable<System.DateTime> Close_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public string Update_User { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
