//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MobileCallogList
    {
        public string Comp_Cd { get; set; }
        public string Sn { get; set; }
        public string Store_Cd { get; set; }
        public string Store_Name { get; set; }
        public string Tel_No { get; set; }
        public string Caller_Name { get; set; }
        public string Store_Addr { get; set; }
        public string Asset_Cd { get; set; }
        public string Asset_Name { get; set; }
        public string Damage_No { get; set; }
        public string Damage_Desc { get; set; }
        public string Fv_Date { get; set; }
        public string Fd_Date { get; set; }
        public string PushUser { get; set; }
        public string AccUser { get; set; }
        public int TimePoint { get; set; }
        public string Call_Desc { get; set; }
        public string Remark_Add { get; set; }
        public string Fi_Date { get; set; }
        public string Call_Level { get; set; }
        public string CallLevelVal { get; set; }
        public string Ast_Type { get; set; }
        public string AstTypeVal { get; set; }
        public string Arrive_Date { get; set; }
        public string Fc_Date { get; set; }
        public string Finish_Id { get; set; }
        public string Finish_Name { get; set; }
        public string Work_Id { get; set; }
        public string Work_Name { get; set; }
        public string Damage_Proc_No { get; set; }
        public string Damage_Proc_No_Val { get; set; }
        public string Work_Desc { get; set; }
        public string Close_Date { get; set; }
        public string Close_User { get; set; }
        public string Img_1 { get; set; }
        public string Img_2 { get; set; }
        public string Img_3 { get; set; }
        public Nullable<decimal> Coffee_Cup { get; set; }
        public string Spc_Asset_Kind { get; set; }
        public string Vender_Cd { get; set; }
    }
}
