//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NewTVENDER
    {
        public string Comp_Cd { get; set; }
        public string Vender_Cd { get; set; }
        public string Vender_Name { get; set; }
        public string Vender_Addr { get; set; }
        public string Vender_Id { get; set; }
        public string Tax_Type { get; set; }
        public string Contact_Window { get; set; }
        public string Tel_No { get; set; }
        public string Fax_No { get; set; }
        public string Email_Account { get; set; }
        public string Holiday_Tel_No { get; set; }
        public string Emc_Tel_No { get; set; }
        public string Show_New_Call { get; set; }
        public string Is_DataTrans { get; set; }
        public string Is_Push { get; set; }
        public string Affiliates { get; set; }
        public string Close_Date { get; set; }
        public string Update_User { get; set; }
        public string Update_Date { get; set; }
        public string Trans_Para { get; set; }
    }
}
