//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ptc.Seteng.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_W33M020
    {
        public long Upd_Seq { get; set; }
        public Nullable<System.DateTime> Last_Date { get; set; }
        public Nullable<System.DateTime> Work_Date { get; set; }
        public Nullable<System.DateTime> Next_Date { get; set; }
        public string Abnormal { get; set; }
        public Nullable<bool> Check_Sts { get; set; }
        public Nullable<bool> Close_Sts { get; set; }
        public string Remark { get; set; }
        public bool Rec_Sts { get; set; }
        public string Update_User { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Asset_Name { get; set; }
        public string Store_Name { get; set; }
        public string Zo_Cd { get; set; }
        public string Zo_Name { get; set; }
        public string Do_Cd { get; set; }
        public string Do_Name { get; set; }
        public string Vender_Cd { get; set; }
        public string Store_Cd { get; set; }
        public string Asset_Cd { get; set; }
        public string Comp_Cd { get; set; }
        public string Tel_No { get; set; }
        public string Store_Addr { get; set; }
        public string Store_Kind { get; set; }
        public Nullable<decimal> Begin_YM { get; set; }
        public string Comp_Short { get; set; }
    }
}
